version: '3'
services:
  jupyter:
    build: .
    image: jupyter-treasure
    container_name: jupyter
    ports:
      - "8080:8080"
    restart: always
    command: jupyter notebook
    privileged: true