version: '3'

volumes:
  mysql-data:
  postgresql-data:
  pgweb-data:

services:
  jupyter:
    links:
      - mysql
    build: .
    image: jupyter-treasure
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ../notebook:/notebook
      - ./config/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
      - ./init/python3/requirements.txt:/tmp/requirements.txt
      - ./config/mysql-jupyter-kernel/mysql_config.json:/root/.local/config/mysql_config.json
    command: jupyter lab
    restart: always
    privileged: true

  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/my.cnf:/etc/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jupyter
      MYSQL_DATABASE: jupyter
      MYSQL_USER: root
      MYSQL_PASSWORD: jupyter

  phpmyadmin:
    links:
      - mysql
    image: phpmyadmin/phpmyadmin:4.8.0-3
    container_name: mysqladmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql:3306
      PMA_USER: root
      PMA_PASSWORD: jupyter
    ports:
      - "8000:80"
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jupyter
      - POSTGRES_USER=use
      - POSTGRES_DB=jupyter
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgresql-data:/var/lib/postgresql/data/pgdata
    restart: always

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://use:jupyter@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
    restart: always